// <autogenerated>
//   This file was generated by T4 code generator RepositoryScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using AppName.Domains;
using AppName.Logic.Repositories;
using System.Data.Entity;

namespace AppName.EFDataAccess
{
	public partial class ProductRepository
	: BaseRepository<Product>, IProductRepository

	{
		public ProductRepository(DataContext db) : base(db)
		{
		}

		protected override DbSet<Product> DbSet{
			get{
				return _db.Products;
				}
		}
	}
}
